name: tailwind_cli
description: A simple yet best tailwind style generation cli tool for flutter projects.
version: 0.7.2
homepage: https://github.com/thedevsbuddy/tailwind_cli

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  dcli: ^3.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
