name: tailwind_cli
description: A simple yet best tailwind style generation cli tool for flutter projects.
version: 0.7.5
homepage: https://github.com/thedevsbuddy/tailwind_cli

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  dcli: ^6.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# flutter:
# assets:
# Binaries
bin:
  tailwind_cli_build: bin/build.dart
  tailwind_cli_init: bin/init.dart
