name: Prepare Release

on:
  push:
    branches:
      - "major/*"
      - "minor/*"
      - "patch/*"

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from branch name
        id: extract_version
        run: |
          BRANCH="${GITHUB_REF#refs/heads/}"

          if [[ "$BRANCH" =~ ^(major|minor|patch)/v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            NEW_VERSION="${BASH_REMATCH[2]}"
            echo "Extracted version: $NEW_VERSION"
            echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          else
            echo "Branch name does not contain a valid version number"
            exit 1
          fi

      - name: Update version in pubspec.yaml
        run: |
          NEW_VERSION="${{ steps.extract_version.outputs.new_version }}"
          sed -i "s/^version: .*/version: $NEW_VERSION/" pubspec.yaml

      - name: Create tag
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_ACCESS_TOKEN }}
        run: |
          NEW_VERSION="${{ steps.extract_version.outputs.new_version }}"
          git config user.name thedevsbuddy
          git config user.email devsbuddy404@gmail.com
          git add pubspec.yaml
          git commit -m "Bump version to $NEW_VERSION"
          git tag "v$NEW_VERSION"
          git push origin "v$NEW_VERSION"
          sleep 10 # Add a short delay

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          NEW_VERSION="${{ steps.extract_version.outputs.new_version }}"
          gh release create "v$NEW_VERSION" \
            --title "Release $NEW_VERSION" \
            --notes "Release notes for version $NEW_VERSION
              
            For full changelog, see [CHANGELOG.md](./CHANGELOG.md)"
